export const API_ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD_STATS: "/dashboard/dashboard-statistic",
  HIGHEST_PURCHASE_ORDERS: "/dashboard/highest-purchase-order",
  USER_REPORT : '/order/users-report',
  ORDER_STATUS_COUNT : '/order/piechart-data',
  ORDER_REPORT : '/order/orders-report',
  LISTOFCATEGORY : '/category/listOfCategories',
  CREATECATEGORY : '/category/addCategory',
  FILEUPLOAD : "/fileUpload",
  UPDATECATEGORY : '/category/updateCategory',
  DELETECATEGORY : '/category/deleteCategory',
  VIEWCATEGORY : '/category/viewCategory',
  CATEGORYDROPDOWN : '/category/categoryDropdown',
  LISTOFPRODUCT : '/products/listOfProducts',
  VIEWPRODUCT : '/products/productViewForAdmin',
  DELETEPRODUCT : "/products/deleteProduct",
  ADDPRODUCT : "/products/addProduct",
  EDITPRODUCT : "/products/editProduct"
};
